CFLAGS += \
	-Iliblcf/src \
	-Iliblcf/src/generated

# ICU LIB ORDER MATTERS; else, icudt75_dat is not defined (why????)

LDFLAGS += \
	-lexpat \
	-licuuc \
	-licudt \
	-licuio \
	-licutu \
	-licuin \
	-licu \
	-linih

liblcf_SRCS = \
	liblcf/src/dbarray.cpp \
	liblcf/src/dbstring_struct.cpp \
	liblcf/src/encoder.cpp \
	liblcf/src/ldb_equipment.cpp \
	liblcf/src/ldb_eventcommand.cpp \
	liblcf/src/ldb_parameters.cpp \
	liblcf/src/ldb_reader.cpp \
	liblcf/src/lmt_reader.cpp \
	liblcf/src/lmt_rect.cpp \
	liblcf/src/lmt_treemap.cpp \
	liblcf/src/lmu_movecommand.cpp \
	liblcf/src/lmu_reader.cpp \
	liblcf/src/lsd_reader.cpp \
	liblcf/src/log_handler.cpp \
	liblcf/src/reader_flags.cpp \
	liblcf/src/reader_lcf.cpp \
	liblcf/src/reader_util.cpp \
	liblcf/src/reader_xml.cpp \
	liblcf/src/rpg_setup.cpp \
	liblcf/src/rpg_terms.cpp \
	liblcf/src/saveopt.cpp \
	liblcf/src/writer_lcf.cpp \
	liblcf/src/writer_xml.cpp \
	liblcf/src/generated/ldb_actor.cpp \
	liblcf/src/generated/ldb_animation.cpp \
	liblcf/src/generated/ldb_animationcelldata.cpp \
	liblcf/src/generated/ldb_animationframe.cpp \
	liblcf/src/generated/ldb_animationtiming.cpp \
	liblcf/src/generated/ldb_attribute.cpp \
	liblcf/src/generated/ldb_battlecommand.cpp \
	liblcf/src/generated/ldb_battlecommands.cpp \
	liblcf/src/generated/ldb_battleranimation.cpp \
	liblcf/src/generated/ldb_battleranimationitemskill.cpp \
	liblcf/src/generated/ldb_battleranimationpose.cpp \
	liblcf/src/generated/ldb_battleranimationweapon.cpp \
	liblcf/src/generated/ldb_chipset.cpp \
	liblcf/src/generated/ldb_class.cpp \
	liblcf/src/generated/ldb_commonevent.cpp \
	liblcf/src/generated/ldb_database.cpp \
	liblcf/src/generated/ldb_enemy.cpp \
	liblcf/src/generated/ldb_enemyaction.cpp \
	liblcf/src/generated/ldb_item.cpp \
	liblcf/src/generated/ldb_learning.cpp \
	liblcf/src/generated/ldb_music.cpp \
	liblcf/src/generated/ldb_skill.cpp \
	liblcf/src/generated/ldb_sound.cpp \
	liblcf/src/generated/ldb_state.cpp \
	liblcf/src/generated/ldb_switch.cpp \
	liblcf/src/generated/ldb_system.cpp \
	liblcf/src/generated/ldb_terms.cpp \
	liblcf/src/generated/ldb_terrain.cpp \
	liblcf/src/generated/ldb_testbattler.cpp \
	liblcf/src/generated/ldb_troop.cpp \
	liblcf/src/generated/ldb_troopmember.cpp \
	liblcf/src/generated/ldb_trooppage.cpp \
	liblcf/src/generated/ldb_trooppagecondition.cpp \
	liblcf/src/generated/ldb_variable.cpp \
	liblcf/src/generated/lmt_encounter.cpp \
	liblcf/src/generated/lmt_mapinfo.cpp \
	liblcf/src/generated/lmt_start.cpp \
	liblcf/src/generated/lmu_event.cpp \
	liblcf/src/generated/lmu_eventpage.cpp \
	liblcf/src/generated/lmu_eventpagecondition.cpp \
	liblcf/src/generated/lmu_map.cpp \
	liblcf/src/generated/lmu_moveroute.cpp \
	liblcf/src/generated/lsd_save.cpp \
	liblcf/src/generated/lsd_saveactor.cpp \
	liblcf/src/generated/lsd_savecommonevent.cpp \
	liblcf/src/generated/lsd_saveeasyrpgdata.cpp \
	liblcf/src/generated/lsd_saveeasyrpgtext.cpp \
	liblcf/src/generated/lsd_saveeasyrpgwindow.cpp \
	liblcf/src/generated/lsd_saveeventexecframe.cpp \
	liblcf/src/generated/lsd_saveeventexecstate.cpp \
	liblcf/src/generated/lsd_saveinventory.cpp \
	liblcf/src/generated/lsd_savemapevent.cpp \
	liblcf/src/generated/lsd_savemapeventbase.cpp \
	liblcf/src/generated/lsd_savemapinfo.cpp \
	liblcf/src/generated/lsd_savepanorama.cpp \
	liblcf/src/generated/lsd_savepartylocation.cpp \
	liblcf/src/generated/lsd_savepicture.cpp \
	liblcf/src/generated/lsd_savescreen.cpp \
	liblcf/src/generated/lsd_savesystem.cpp \
	liblcf/src/generated/lsd_savetarget.cpp \
	liblcf/src/generated/lsd_savetitle.cpp \
	liblcf/src/generated/lsd_savevehiclelocation.cpp \
	liblcf/src/generated/rpg_actor.cpp \
	liblcf/src/generated/rpg_animation.cpp \
	liblcf/src/generated/rpg_animationcelldata.cpp \
	liblcf/src/generated/rpg_animationframe.cpp \
	liblcf/src/generated/rpg_animationtiming.cpp \
	liblcf/src/generated/rpg_attribute.cpp \
	liblcf/src/generated/rpg_battlecommand.cpp \
	liblcf/src/generated/rpg_battlecommands.cpp \
	liblcf/src/generated/rpg_battleranimation.cpp \
	liblcf/src/generated/rpg_battleranimationitemskill.cpp \
	liblcf/src/generated/rpg_battleranimationpose.cpp \
	liblcf/src/generated/rpg_battleranimationweapon.cpp \
	liblcf/src/generated/rpg_chipset.cpp \
	liblcf/src/generated/rpg_class.cpp \
	liblcf/src/generated/rpg_commonevent.cpp \
	liblcf/src/generated/rpg_database.cpp \
	liblcf/src/generated/rpg_encounter.cpp \
	liblcf/src/generated/rpg_enemy.cpp \
	liblcf/src/generated/rpg_enemyaction.cpp \
	liblcf/src/generated/rpg_equipment.cpp \
	liblcf/src/generated/rpg_event.cpp \
	liblcf/src/generated/rpg_eventcommand.cpp \
	liblcf/src/generated/rpg_eventpage.cpp \
	liblcf/src/generated/rpg_eventpagecondition.cpp \
	liblcf/src/generated/rpg_item.cpp \
	liblcf/src/generated/rpg_learning.cpp \
	liblcf/src/generated/rpg_map.cpp \
	liblcf/src/generated/rpg_mapinfo.cpp \
	liblcf/src/generated/rpg_movecommand.cpp \
	liblcf/src/generated/rpg_moveroute.cpp \
	liblcf/src/generated/rpg_music.cpp \
	liblcf/src/generated/rpg_parameters.cpp \
	liblcf/src/generated/rpg_rect.cpp \
	liblcf/src/generated/rpg_save.cpp \
	liblcf/src/generated/rpg_saveactor.cpp \
	liblcf/src/generated/rpg_savecommonevent.cpp \
	liblcf/src/generated/rpg_saveeasyrpgdata.cpp \
	liblcf/src/generated/rpg_saveeasyrpgtext.cpp \
	liblcf/src/generated/rpg_saveeasyrpgwindow.cpp \
	liblcf/src/generated/rpg_saveeventexecframe.cpp \
	liblcf/src/generated/rpg_saveeventexecstate.cpp \
	liblcf/src/generated/rpg_saveinventory.cpp \
	liblcf/src/generated/rpg_savemapevent.cpp \
	liblcf/src/generated/rpg_savemapeventbase.cpp \
	liblcf/src/generated/rpg_savemapinfo.cpp \
	liblcf/src/generated/rpg_savepanorama.cpp \
	liblcf/src/generated/rpg_savepartylocation.cpp \
	liblcf/src/generated/rpg_savepicture.cpp \
	liblcf/src/generated/rpg_savescreen.cpp \
	liblcf/src/generated/rpg_savesystem.cpp \
	liblcf/src/generated/rpg_savetarget.cpp \
	liblcf/src/generated/rpg_savetitle.cpp \
	liblcf/src/generated/rpg_savevehiclelocation.cpp \
	liblcf/src/generated/rpg_skill.cpp \
	liblcf/src/generated/rpg_sound.cpp \
	liblcf/src/generated/rpg_start.cpp \
	liblcf/src/generated/rpg_state.cpp \
	liblcf/src/generated/rpg_switch.cpp \
	liblcf/src/generated/rpg_system.cpp \
	liblcf/src/generated/rpg_terms.cpp \
	liblcf/src/generated/rpg_terrain.cpp \
	liblcf/src/generated/rpg_testbattler.cpp \
	liblcf/src/generated/rpg_treemap.cpp \
	liblcf/src/generated/rpg_troop.cpp \
	liblcf/src/generated/rpg_troopmember.cpp \
	liblcf/src/generated/rpg_trooppage.cpp \
	liblcf/src/generated/rpg_trooppagecondition.cpp \
	liblcf/src/generated/rpg_variable.cpp

